service: onboarding-example-backend

provider:
  name: aws
  profile: bee2pay-sandbox
  region: sa-east-1
  stage: ${{opt:stage, 'dev'}}
  variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"
  environment:
    STAGE: ${{self:provider.stage}}

package:
  exclude:
    - node_modules/**
    - __pycache__/**

functions:
  helloWorld:
    handler: src.helloWorld.lambda_function.lambda_handler
    runtime: python3.7
