yarnPath: ".yarn/releases/yarn-berry.cjs"

nodeLinker: node-modules

npmScopes:
  bo-angular:
    npmRegistryServer: "https://tfs.omnibees.com/tfs/IDTProjects/_packaging/Bo-Angular%40Local/npm/registry/"
  niaratech:
    npmRegistryServer: "https://tfs.omnibees.com/tfs/IDTProjects/_packaging/niaratech/npm/registry/"